# Generated by Django 4.2.3 on 2023-08-30 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_title', models.CharField(max_length=150, verbose_name='Название категории')),
                ('category_title_ru', models.CharField(max_length=150, null=True, verbose_name='Название категории')),
                ('category_title_en', models.CharField(max_length=150, null=True, verbose_name='Название категории')),
                ('category_title_uz', models.CharField(max_length=150, null=True, verbose_name='Название категории')),
                ('archive', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'permissions': [('add_category', 'Добавить категорию'), ('view_category', 'Просмотреть категорию'), ('change_category', 'Изменить категорию'), ('delete_category', 'Удалить категорию')],
                'default_permissions': (),
            },
        ),
    ]
