# Generated by Django 4.2.3 on 2025-01-16 00:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("category", "0002_remove_category_archive_remove_category_deleted"),
    ]

    operations = [
        migrations.CreateModel(
            name="XRayCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(max_length=150, verbose_name="Название категории"),
                ),
                (
                    "name_en",
                    models.CharField(
                        max_length=150, null=True, verbose_name="Название категории"
                    ),
                ),
                (
                    "name_uz",
                    models.CharField(
                        max_length=150, null=True, verbose_name="Название категории"
                    ),
                ),
                (
                    "name_ru",
                    models.CharField(
                        max_length=150, null=True, verbose_name="Название категории"
                    ),
                ),
                (
                    "order_index",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория Рентгена",
                "verbose_name_plural": "Категории Рентгена",
                "permissions": [
                    ("add_xraycategory", "Добавить категорию рентгена"),
                    ("view_xraycategory", "Просмотреть категорию рентгена"),
                    ("change_xraycategory", "Изменить категорию рентгена"),
                    ("delete_xraycategory", "Удалить категорию рентгена"),
                ],
                "default_permissions": (),
            },
        ),
        migrations.AddConstraint(
            model_name="xraycategory",
            constraint=models.UniqueConstraint(
                fields=("name",), name="unique_x_ray_categories_name"
            ),
        ),
    ]
