# Generated by Django 4.2.3 on 2025-01-18 13:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("work", "0003_work_x_ray_categories"),
        ("category", "0003_xraycategory_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="XRayCategory",
            new_name="PrintOutCategory",
        ),
        migrations.AlterModelOptions(
            name="printoutcategory",
            options={
                "default_permissions": (),
                "permissions": [
                    ("add_printoutcategory", "Добавить категорию распечатки"),
                    ("view_printoutcategory", "Просмотреть категорию распечатки"),
                    ("change_printoutcategory", "Изменить категорию распечатки"),
                    ("delete_printoutcategory", "Удалить категорию распечатки"),
                ],
                "verbose_name": "Категория Распечатки",
                "verbose_name_plural": "Категории Распечатки",
            },
        ),
        migrations.RemoveConstraint(
            model_name="printoutcategory",
            name="unique_x_ray_categories_name",
        ),
        migrations.AddConstraint(
            model_name="printoutcategory",
            constraint=models.UniqueConstraint(
                fields=("name",), name="unique_print_out_categories_name"
            ),
        ),
    ]
