# Generated by Django 4.2.3 on 2026-01-10 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_rename_xraycategory_printoutcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_icon',
            field=models.ImageField(default=None, upload_to='categories/', verbose_name='Значок категории'),
            preserve_default=False,
        ),
    ]
