# Generated by Django 4.2.3 on 2026-01-10 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_category_category_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_icon',
            field=models.ImageField(null=True, upload_to='categories/', verbose_name='Значок категории'),
        ),
    ]
