# Generated by Django 4.2.3 on 2024-08-04 22:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0004_client_client_last_viewed_at_and_more'),
        ('transaction', '0002_initial'),
        ('user', '0003_user_user_auth_code_user_user_code_max_try_and_more'),
        ('credit', '0003_initial'),
        ('medcard', '0004_remove_action_action_time'),
        ('expenses', '0005_remove_financialreport_report_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalCardReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(blank=True, max_length=255, null=True)),
                ('client_phone', models.CharField(blank=True, max_length=255, null=True)),
                ('doctor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_card_reports', to='medcard.action')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_card_reports', to='client.client')),
                ('credits', models.ManyToManyField(related_name='medical_card_reports', to='credit.credit')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_card_reports', to=settings.AUTH_USER_MODEL)),
                ('financial_reports', models.ManyToManyField(related_name='medical_card_reports', to='expenses.financialreport')),
                ('salaries', models.ManyToManyField(related_name='medical_card_reports', to='user.usersalary')),
                ('transactions', models.ManyToManyField(related_name='medical_card_reports', to='transaction.transaction')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_card_reports_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Отчет по медкарте',
                'verbose_name_plural': 'Отчеты по медкарте',
                'permissions': [('view_medicalcardreport', 'Просмотреть финансовый отчет'), ('change_medicalcardreport', 'Изменить финансовый отчет')],
                'default_permissions': (),
            },
        ),
    ]
