# Generated by Django 4.2.3 on 2024-01-30 00:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
