# Generated by Django 4.2.3 on 2024-05-05 00:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_alter_client_client_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_last_viewed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='Client_Private_Phone',
        ),
    ]
