# Generated by Django 4.2.3 on 2025-02-13 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0004_client_client_last_viewed_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="note",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="client_public_phone",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="client_public_phone",
                to="client.client",
                verbose_name="Клиент",
            ),
        ),
        migrations.CreateModel(
            name="ClientAnamnesis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contact_reason",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("treatment_history", models.TextField()),
                ("hiv", models.BooleanField(default=False)),
                (
                    "hepatitis",
                    models.CharField(
                        choices=[("B", "B"), ("С", "С"), ("no", "No")], max_length=50
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anamnesis",
                        to="client.client",
                    ),
                ),
            ],
            options={
                "verbose_name": "Анамнез",
                "verbose_name_plural": "Анамнез",
                "permissions": [
                    ("add_clientanamnesis", "Добавить анамнез"),
                    ("view_clientanamnesis", "Просмотреть анамнез"),
                    ("change_clientanamnesis", "Изменить анамнез"),
                    ("delete_clientanamnesis", "Удалить анамнез"),
                ],
                "default_permissions": (),
            },
        ),
    ]
