# Generated by Django 4.2.3 on 2026-01-10 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article_id', models.AutoField(primary_key=True, serialize=False)),
                ('article_type', models.CharField(choices=[('general_info', 'General information'), ('achievements', 'Our achievements'), ('laboratory', 'Laboratory'), ('comments', 'Comments')], max_length=50, verbose_name='Тип статьи')),
                ('article_title', models.CharField(max_length=255, null=True, verbose_name='Заголовок статьи')),
                ('article_title_en', models.CharField(max_length=255, null=True, verbose_name='Заголовок статьи')),
                ('article_title_uz', models.CharField(max_length=255, null=True, verbose_name='Заголовок статьи')),
                ('article_title_ru', models.CharField(max_length=255, null=True, verbose_name='Заголовок статьи')),
                ('article_body', models.TextField(null=True, verbose_name='Текст статьи')),
                ('article_body_en', models.TextField(null=True, verbose_name='Текст статьи')),
                ('article_body_uz', models.TextField(null=True, verbose_name='Текст статьи')),
                ('article_body_ru', models.TextField(null=True, verbose_name='Текст статьи')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ArticleImage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('photo_id', models.AutoField(primary_key=True, serialize=False)),
                ('article_image', models.ImageField(upload_to='articles/')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='about.article')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
