# Generated by Django 4.2.3 on 2026-01-11 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_body',
            field=models.TextField(blank=True, null=True, verbose_name='Текст статьи'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_body_en',
            field=models.TextField(blank=True, null=True, verbose_name='Текст статьи'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_body_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Текст статьи'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_body_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Текст статьи'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок статьи'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок статьи'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок статьи'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_title_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок статьи'),
        ),
    ]
