# Generated by Django 4.2.3 on 2026-03-22 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_alter_article_article_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_type',
            field=models.CharField(choices=[('general_info', 'General information'), ('achievements', 'Our achievements'), ('laboratory', 'Laboratory'), ('comments', 'Comments'), ('news', 'News')], max_length=50, verbose_name='Тип статьи'),
        ),
    ]
