# Generated by Django 4.2.3 on 2026-04-09 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_contractdocument_doc_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.TextField()),
                ('location_latt', models.CharField(max_length=20)),
                ('location_long', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=15)),
                ('telegram', models.CharField(blank=True, max_length=15, null=True)),
                ('facebook', models.CharField(blank=True, max_length=15, null=True)),
                ('instagram', models.CharField(blank=True, max_length=15, null=True)),
                ('youtube', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TermsAndConditions',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('text_type', models.CharField(choices=[('privacy_policy', 'Privacy policy'), ('terms_and_conditions', 'Terms and conditions'), ('about_app', 'About app'), ('reservation_notes', 'Reservation notes')], default='privacy_policy', max_length=50)),
                ('text', models.TextField()),
                ('text_en', models.TextField(null=True)),
                ('text_uz', models.TextField(null=True)),
                ('text_ru', models.TextField(null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='contractdocument',
            name='doc_type',
        ),
        migrations.RemoveField(
            model_name='contractdocument',
            name='title',
        ),
    ]
