# Generated by Django 4.2.3 on 2026-03-22 13:28

import apps.vacancies.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('vacancy_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Название вакансии')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Название вакансии')),
                ('title_uz', models.CharField(max_length=255, null=True, verbose_name='Название вакансии')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Название вакансии')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('description_uz', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('requirements', models.TextField(blank=True, null=True, verbose_name='Требования')),
                ('requirements_en', models.TextField(blank=True, null=True, verbose_name='Требования')),
                ('requirements_uz', models.TextField(blank=True, null=True, verbose_name='Требования')),
                ('requirements_ru', models.TextField(blank=True, null=True, verbose_name='Требования')),
                ('responsibilities', models.TextField(blank=True, null=True, verbose_name='Обязанности')),
                ('responsibilities_en', models.TextField(blank=True, null=True, verbose_name='Обязанности')),
                ('responsibilities_uz', models.TextField(blank=True, null=True, verbose_name='Обязанности')),
                ('responsibilities_ru', models.TextField(blank=True, null=True, verbose_name='Обязанности')),
                ('conditions', models.TextField(blank=True, null=True, verbose_name='Условия')),
                ('conditions_en', models.TextField(blank=True, null=True, verbose_name='Условия')),
                ('conditions_uz', models.TextField(blank=True, null=True, verbose_name='Условия')),
                ('conditions_ru', models.TextField(blank=True, null=True, verbose_name='Условия')),
                ('salary_from', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Зарплата от')),
                ('salary_to', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Зарплата до')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Контактный телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Контактный email')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Срок подачи')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
                'ordering': ['sort_order', '-created_at'],
                'permissions': [('add_vacancy', 'Добавить вакансию'), ('view_vacancy', 'Просмотреть вакансию'), ('change_vacancy', 'Изменить вакансию'), ('delete_vacancy', 'Удалить вакансию')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='VacancyApplication',
            fields=[
                ('application_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Мужской'), ('female', 'Женский')], max_length=20, null=True, verbose_name='Пол')),
                ('marital_status', models.CharField(blank=True, choices=[('single', 'Холост / Не замужем'), ('married', 'Женат / Замужем'), ('divorced', 'Разведен(а)'), ('widowed', 'Вдовец / Вдова')], max_length=20, null=True, verbose_name='Семейное положение')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Сообщение')),
                ('resume_file', models.FileField(upload_to=apps.vacancies.models.VacancyResumePathAndRename('vacancies/resumes'), verbose_name='Резюме')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_review', 'На рассмотрении'), ('accepted', 'Принято'), ('rejected', 'Отклонено')], default='new', max_length=20, verbose_name='Статус')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='vacancies.vacancy', verbose_name='Вакансия')),
            ],
            options={
                'verbose_name': 'Отклик на вакансию',
                'verbose_name_plural': 'Отклики на вакансии',
                'ordering': ['-created_at'],
                'permissions': [('add_vacancyapplication', 'Добавить отклик на вакансию'), ('view_vacancyapplication', 'Просмотреть отклик на вакансию'), ('change_vacancyapplication', 'Изменить отклик на вакансию'), ('delete_vacancyapplication', 'Удалить отклик на вакансию')],
                'default_permissions': (),
            },
        ),
    ]
