# Generated by Django 4.2.3 on 2023-08-30 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('task_description', models.TextField(verbose_name='Содержание Задачи')),
                ('task_priority', models.CharField(choices=[('Высокий', 'Высокий'), ('Низкий', 'Низкий'), ('Обычный', 'Обычный')], default='Обычный', max_length=50, verbose_name='Приоритет Задачи')),
                ('task_deadline', models.DateTimeField(verbose_name='Дедлайн Задачи')),
                ('task_finished', models.BooleanField(default=False, verbose_name='Сделано')),
                ('archive', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'permissions': [('add_task', 'Добавить задачу'), ('view_task', 'Просмотреть задачу'), ('change_task', 'Изменить задачу'), ('delete_task', 'Удалить задачу')],
                'default_permissions': (),
            },
        ),
    ]
