# Generated by Django 4.2.3 on 2023-08-30 20:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_from', to=settings.AUTH_USER_MODEL, verbose_name='От кого Задача'),
        ),
        migrations.AddField(
            model_name='task',
            name='task_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_to', to=settings.AUTH_USER_MODEL, verbose_name='Для кого Задача'),
        ),
    ]
