# Generated by Django 4.2.3 on 2023-08-30 20:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import apps.user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('specialization', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('work', '0001_initial'),
        ('medcard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(db_index=True, max_length=150, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('user_firstname', models.CharField(blank=True, max_length=50, null=True, verbose_name='Имя')),
                ('user_lastname', models.CharField(blank=True, max_length=50, null=True, verbose_name='Фамилия')),
                ('user_father_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Отчество')),
                ('user_birthdate', models.DateField(blank=True, null=True, verbose_name='Дата Рождения')),
                ('user_gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20, null=True, verbose_name='Пол')),
                ('user_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес')),
                ('user_citizenship', models.CharField(blank=True, choices=[('AD', 'Andorra'), ('AE', 'United Arab Emirates'), ('AF', 'Afghanistan'), ('AG', 'Antigua & Barbuda'), ('AI', 'Anguilla'), ('AL', 'Albania'), ('AM', 'Armenia'), ('AN', 'Netherlands Antilles'), ('AO', 'Angola'), ('AQ', 'Antarctica'), ('AR', 'Argentina'), ('AS', 'American Samoa'), ('AT', 'Austria'), ('AU', 'Australia'), ('AW', 'Aruba'), ('AZ', 'Azerbaijan'), ('BA', 'Bosnia and Herzegovina'), ('BB', 'Barbados'), ('BD', 'Bangladesh'), ('BE', 'Belgium'), ('BF', 'Burkina Faso'), ('BG', 'Bulgaria'), ('BH', 'Bahrain'), ('BI', 'Burundi'), ('BJ', 'Benin'), ('BM', 'Bermuda'), ('BN', 'Brunei Darussalam'), ('BO', 'Bolivia'), ('BR', 'Brazil'), ('BS', 'Bahama'), ('BT', 'Bhutan'), ('BV', 'Bouvet Island'), ('BW', 'Botswana'), ('BY', 'Belarus'), ('BZ', 'Belize'), ('CA', 'Canada'), ('CC', 'Cocos (Keeling) Islands'), ('CF', 'Central African Republic'), ('CG', 'Congo'), ('CH', 'Switzerland'), ('CI', 'Ivory Coast'), ('CK', 'Cook Iislands'), ('CL', 'Chile'), ('CM', 'Cameroon'), ('CN', 'China'), ('CO', 'Colombia'), ('CR', 'Costa Rica'), ('CU', 'Cuba'), ('CV', 'Cape Verde'), ('CX', 'Christmas Island'), ('CY', 'Cyprus'), ('CZ', 'Czech Republic'), ('DE', 'Germany'), ('DJ', 'Djibouti'), ('DK', 'Denmark'), ('DM', 'Dominica'), ('DO', 'Dominican Republic'), ('DZ', 'Algeria'), ('EC', 'Ecuador'), ('EE', 'Estonia'), ('EG', 'Egypt'), ('EH', 'Western Sahara'), ('ER', 'Eritrea'), ('ES', 'Spain'), ('ET', 'Ethiopia'), ('FI', 'Finland'), ('FJ', 'Fiji'), ('FK', 'Falkland Islands (Malvinas)'), ('FM', 'Micronesia'), ('FO', 'Faroe Islands'), ('FR', 'France'), ('FX', 'France, Metropolitan'), ('GA', 'Gabon'), ('GB', 'United Kingdom (Great Britain)'), ('GD', 'Grenada'), ('GE', 'Georgia'), ('GF', 'French Guiana'), ('GH', 'Ghana'), ('GI', 'Gibraltar'), ('GL', 'Greenland'), ('GM', 'Gambia'), ('GN', 'Guinea'), ('GP', 'Guadeloupe'), ('GQ', 'Equatorial Guinea'), ('GR', 'Greece'), ('GS', 'South Georgia and the South Sandwich Islands'), ('GT', 'Guatemala'), ('GU', 'Guam'), ('GW', 'Guinea-Bissau'), ('GY', 'Guyana'), ('HK', 'Hong Kong'), ('HM', 'Heard & McDonald Islands'), ('HN', 'Honduras'), ('HR', 'Croatia'), ('HT', 'Haiti'), ('HU', 'Hungary'), ('ID', 'Indonesia'), ('IE', 'Ireland'), ('IL', 'Israel'), ('IN', 'India'), ('IO', 'British Indian Ocean Territory'), ('IQ', 'Iraq'), ('IR', 'Islamic Republic of Iran'), ('IS', 'Iceland'), ('IT', 'Italy'), ('JM', 'Jamaica'), ('JO', 'Jordan'), ('JP', 'Japan'), ('KE', 'Kenya'), ('KG', 'Kyrgyzstan'), ('KH', 'Cambodia'), ('KI', 'Kiribati'), ('KM', 'Comoros'), ('KN', 'St. Kitts and Nevis'), ('KP', "Korea, Democratic People's Republic of"), ('KR', 'Korea, Republic of'), ('KW', 'Kuwait'), ('KY', 'Cayman Islands'), ('KZ', 'Kazakhstan'), ('LA', "Lao People's Democratic Republic"), ('LB', 'Lebanon'), ('LC', 'Saint Lucia'), ('LI', 'Liechtenstein'), ('LK', 'Sri Lanka'), ('LR', 'Liberia'), ('LS', 'Lesotho'), ('LT', 'Lithuania'), ('LU', 'Luxembourg'), ('LV', 'Latvia'), ('LY', 'Libyan Arab Jamahiriya'), ('MA', 'Morocco'), ('MC', 'Monaco'), ('MD', 'Moldova, Republic of'), ('MG', 'Madagascar'), ('MH', 'Marshall Islands'), ('ML', 'Mali'), ('MN', 'Mongolia'), ('MM', 'Myanmar'), ('MO', 'Macau'), ('MP', 'Northern Mariana Islands'), ('MQ', 'Martinique'), ('MR', 'Mauritania'), ('MS', 'Monserrat'), ('MT', 'Malta'), ('MU', 'Mauritius'), ('MV', 'Maldives'), ('MW', 'Malawi'), ('MX', 'Mexico'), ('MY', 'Malaysia'), ('MZ', 'Mozambique'), ('NA', 'Namibia'), ('NC', 'New Caledonia'), ('NE', 'Niger'), ('NF', 'Norfolk Island'), ('NG', 'Nigeria'), ('NI', 'Nicaragua'), ('NL', 'Netherlands'), ('NO', 'Norway'), ('NP', 'Nepal'), ('NR', 'Nauru'), ('NU', 'Niue'), ('NZ', 'New Zealand'), ('OM', 'Oman'), ('PA', 'Panama'), ('PE', 'Peru'), ('PF', 'French Polynesia'), ('PG', 'Papua New Guinea'), ('PH', 'Philippines'), ('PK', 'Pakistan'), ('PL', 'Poland'), ('PM', 'St. Pierre & Miquelon'), ('PN', 'Pitcairn'), ('PR', 'Puerto Rico'), ('PT', 'Portugal'), ('PW', 'Palau'), ('PY', 'Paraguay'), ('QA', 'Qatar'), ('RE', 'Reunion'), ('RO', 'Romania'), ('RU', 'Russian Federation'), ('RW', 'Rwanda'), ('SA', 'Saudi Arabia'), ('SB', 'Solomon Islands'), ('SC', 'Seychelles'), ('SD', 'Sudan'), ('SE', 'Sweden'), ('SG', 'Singapore'), ('SH', 'St. Helena'), ('SI', 'Slovenia'), ('SJ', 'Svalbard & Jan Mayen Islands'), ('SK', 'Slovakia'), ('SL', 'Sierra Leone'), ('SM', 'San Marino'), ('SN', 'Senegal'), ('SO', 'Somalia'), ('SR', 'Suriname'), ('ST', 'Sao Tome & Principe'), ('SV', 'El Salvador'), ('SY', 'Syrian Arab Republic'), ('SZ', 'Swaziland'), ('TC', 'Turks & Caicos Islands'), ('TD', 'Chad'), ('TF', 'French Southern Territories'), ('TG', 'Togo'), ('TH', 'Thailand'), ('TJ', 'Tajikistan'), ('TK', 'Tokelau'), ('TM', 'Turkmenistan'), ('TN', 'Tunisia'), ('TO', 'Tonga'), ('TP', 'East Timor'), ('TR', 'Turkey'), ('TT', 'Trinidad & Tobago'), ('TV', 'Tuvalu'), ('TW', 'Taiwan, Province of China'), ('TZ', 'Tanzania, United Republic of'), ('UA', 'Ukraine'), ('UG', 'Uganda'), ('UM', 'United States Minor Outlying Islands'), ('US', 'United States of America'), ('UY', 'Uruguay'), ('UZ', 'Uzbekistan'), ('VA', 'Vatican City State (Holy See)'), ('VC', 'St. Vincent & the Grenadines'), ('VE', 'Venezuela'), ('VG', 'British Virgin Islands'), ('VI', 'United States Virgin Islands'), ('VN', 'Viet Nam'), ('VU', 'Vanuatu'), ('WF', 'Wallis & Futuna Islands'), ('WS', 'Samoa'), ('YE', 'Yemen'), ('YT', 'Mayotte'), ('YU', 'Yugoslavia'), ('ZA', 'South Africa'), ('ZM', 'Zambia'), ('ZR', 'Zaire'), ('ZW', 'Zimbabwe'), ('ZZ', 'Unknown or unspecified country')], max_length=100, null=True, verbose_name='Гражданство')),
                ('user_telegram', models.CharField(blank=True, max_length=255, null=True, verbose_name='Телеграм')),
                ('user_on_place', models.BooleanField(blank=True, default=True, null=True, verbose_name='На рабочем месте')),
                ('user_is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='Активный')),
                ('user_salary_percent', models.IntegerField(default=0, verbose_name='Зарплата сотрудника')),
                ('user_salary_child_percent', models.IntegerField(default=0, verbose_name='Зарплата сотрудника (детский)')),
                ('user_has_car', models.BooleanField(blank=True, default=False, null=True, verbose_name='Личный Транспорт')),
                ('user_image', models.ImageField(blank=True, null=True, upload_to=apps.user.models.PathAndRename('users/'), verbose_name='Фотография')),
                ('archive', models.BooleanField(blank=True, default=False, null=True)),
                ('deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('user_specialization', models.ManyToManyField(blank=True, related_name='user_specialization', to='specialization.specialization', verbose_name='Специализация')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'permissions': [('add_user', 'Добавить пользователя'), ('view_user', 'Просмотреть пользователя'), ('change_user', 'Изменить пользователя'), ('delete_user', 'Удалить пользователя'), ('view_user_private_info', 'Просмотреть приватные данные пользователя'), ('change_user_private_info', 'Изменить приватные данные пользователя'), ('view_user_schedule', 'Просмотреть график работы пользователя'), ('view_user_permissions', 'Просмотреть права доступа пользователя'), ('change_user_schedule', 'Изменить график работы пользователя'), ('change_password', 'Изменить пароль пользователя')],
                'default_permissions': (),
            },
            managers=[
                ('objects', apps.user.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='User_Type',
            fields=[
                ('user_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_text', models.CharField(max_length=255)),
                ('type_text_ru', models.CharField(max_length=255, null=True)),
                ('type_text_en', models.CharField(max_length=255, null=True)),
                ('type_text_uz', models.CharField(max_length=255, null=True)),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Тип пользователя',
                'verbose_name_plural': 'Тип пользователей',
                'permissions': [('add_user_type', 'Добавить тип пользователя'), ('view_user_type', 'Просмотреть тип пользователя'), ('change_user_type', 'Изменить тип пользователя'), ('delete_user_type', 'Удалить тип пользователя')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='UserSchedule',
            fields=[
                ('schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('day', models.CharField(max_length=100)),
                ('work_start_time', models.TimeField()),
                ('work_end_time', models.TimeField()),
                ('lunch_start_time', models.TimeField(blank=True, null=True)),
                ('lunch_end_time', models.TimeField(blank=True, null=True)),
                ('is_working', models.BooleanField(default=True)),
                ('one_time_update', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_schedule', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'График Работы',
                'verbose_name_plural': 'Графики Работ',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='UserSalary',
            fields=[
                ('salary_id', models.AutoField(primary_key=True, serialize=False)),
                ('salary_work_type', models.CharField(max_length=100, verbose_name='Тип зарплаты')),
                ('salary_action_price', models.FloatField(blank=True, null=True, verbose_name='Цена работы медкарты')),
                ('salary_work_price', models.FloatField(blank=True, null=True, verbose_name='Цена работы')),
                ('salary_amount', models.FloatField(blank=True, null=True, verbose_name='Сумма')),
                ('salary_is_paid', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('salary_action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_action', to='medcard.action', verbose_name='Зарплата за работу медкарты')),
                ('salary_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_card', to='medcard.medicalcard', verbose_name='Зарплата по медкарте')),
                ('salary_for_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_for_user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('salary_work', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_work', to='work.work', verbose_name='Зарплата за работу')),
            ],
            options={
                'verbose_name': 'Зарплата сотрудников',
                'verbose_name_plural': 'Зарплаты сотрудников',
                'permissions': [('add_usersalary', 'Добавить зарплату сотрудника'), ('view_usersalary', 'Просмотреть зарплату сотрудника'), ('change_usersalary', 'Изменить зарплату сотрудника'), ('delete_usersalary', 'Удалить зарплату сотрудника')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='User_Public_Phone',
            fields=[
                ('user_phone_id', models.AutoField(primary_key=True, serialize=False)),
                ('public_phone', models.CharField(max_length=255, verbose_name='Публичный номер')),
                ('deleted', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_public_phone', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'Публичный номер пользователя',
                'verbose_name_plural': 'Публичные номера пользователей',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='User_Private_Phone',
            fields=[
                ('user_phone_id', models.AutoField(primary_key=True, serialize=False)),
                ('private_phone', models.CharField(max_length=255, verbose_name='Приватный номер')),
                ('deleted', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_private_phone', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'Приватный номер пользователя',
                'verbose_name_plural': 'Приватные номера пользователей',
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_type', to='user.user_type'),
        ),
    ]
