# Generated by Django 4.2.3 on 2023-11-20 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_color',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Цвет'),
        ),
    ]
