# Generated by Django 4.2.3 on 2024-01-30 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_user_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_auth_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_code_max_try',
            field=models.CharField(default=2, max_length=1),
        ),
        migrations.AddField(
            model_name='user',
            name='user_code_period',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_is_active',
            field=models.BooleanField(blank=True, null=True, verbose_name='Активный'),
        ),
    ]
