# Generated by Django 4.2.3 on 2025-01-25 14:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_user_user_auth_code_user_user_code_max_try_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_gender",
            field=models.CharField(
                choices=[("Male", "Male"), ("Female", "Female")],
                default="Male",
                max_length=20,
                verbose_name="Пол",
            ),
        ),
    ]
