# Generated by Django 4.2.3 on 2023-08-30 20:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('credit', '0002_initial'),
        ('client', '0001_initial'),
        ('medcard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('transaction_type', models.CharField(choices=[('Give credit', 'Give credit'), ('Paid credit', 'Paid credit'), ('Vip credit', 'Vip credit'), ('Partial pay credit', 'Partial pay credit'), ('Forgive credit', 'Forgive credit'), ('Pay for action', 'Pay for action'), ('Partial pay for action', 'Pay for action'), ('Refund credit', 'Refund credit'), ('Refill client balance', 'Refill client balance'), ('Refund client balance', 'Refund client balance')], max_length=100, verbose_name='Тип Транзакции')),
                ('transaction_payment_type', models.CharField(choices=[('Cash', 'Cash'), ('Online transfer', 'Online transfer'), ('Terminal', 'Terminal'), ('Another', 'Another')], default='Cash', max_length=50, verbose_name='Тип Оплаты')),
                ('transaction_sum', models.FloatField(blank=True, default=0, verbose_name='Сумма полученных денег')),
                ('transaction_action_price', models.FloatField(blank=True, default=0, verbose_name='Сумма к оплате')),
                ('transaction_discount_price', models.FloatField(blank=True, default=0, verbose_name='Сумма скидки')),
                ('transaction_discount_percent', models.IntegerField(blank=True, default=0, verbose_name='Процент скидки')),
                ('transaction_work_basic_price', models.FloatField(blank=True, default=0, verbose_name='Цена работы')),
                ('transaction_work_vip_price', models.FloatField(blank=True, default=0, verbose_name='Цена работы (vip)')),
                ('transaction_work_discount_price', models.FloatField(blank=True, default=0, verbose_name='Сумма скидки работы')),
                ('transaction_work_discount_percent', models.IntegerField(blank=True, default=0, verbose_name='Процент скидки работы')),
                ('transaction_card_discount_price', models.FloatField(blank=True, default=0, verbose_name='Сумма скидки с мед-карты')),
                ('transaction_card_discount_percent', models.IntegerField(blank=True, default=0, verbose_name='Процент скидки с мед-карты')),
                ('transaction_benefit', models.FloatField(blank=True, default=0, verbose_name='Прибыль с работы')),
                ('transaction_loss', models.FloatField(blank=True, default=0, verbose_name='Утеря денег с работы')),
                ('transaction_created_at', models.DateTimeField(auto_now_add=True, verbose_name='Транзакция создана')),
                ('transaction_updated_at', models.DateTimeField(auto_now=True, verbose_name='Транзакция обновлена')),
                ('transaction_action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_action', to='medcard.action', verbose_name='Работа клиента')),
                ('transaction_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_card', to='medcard.medicalcard', verbose_name='Медкарта клиента')),
                ('transaction_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_client', to='client.client', verbose_name='Клиент')),
                ('transaction_credit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_credit', to='credit.credit', verbose_name='Транзакция за кредит')),
                ('transaction_receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_receiver', to='client.client', verbose_name='Получатель')),
            ],
            options={
                'verbose_name': 'Транзакция',
                'verbose_name_plural': 'Транзакции',
                'permissions': [('add_transaction', 'Добавить транзакцию'), ('view_transaction', 'Просмотреть транзакцию'), ('change_transaction', 'Изменить транзакцию'), ('delete_transaction', 'Удалить транзакцию')],
                'default_permissions': (),
            },
        ),
    ]
