# Generated by Django 4.2.3 on 2025-01-25 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0005_remove_financialreport_report_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("transaction", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="financial_report",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="expenses.financialreport",
                verbose_name="Финансовый отчет",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions_updated_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Обновлен пользователем",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_payment_type",
            field=models.CharField(
                choices=[
                    ("cash", "Cash"),
                    ("online_transfer", "Online transfer"),
                    ("terminal", "Card"),
                    ("another", "Another"),
                ],
                default="cash",
                max_length=50,
                verbose_name="Тип Оплаты",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("give_credit", "Give credit"),
                    ("paid_credit", "Paid credit"),
                    ("vip_credit", "Vip credit"),
                    ("partial_pay_credit", "Partially paid credit"),
                    ("forgive_credit", "Forgiven credit"),
                    ("pay_for_action", "Payment for medical card action"),
                    (
                        "partial_pay_for_action",
                        "Partial payment for medical card action",
                    ),
                    ("refill_client_balance", "Refilled client balance"),
                    ("refund_client_balance", "Refunded client balance"),
                ],
                max_length=100,
                verbose_name="Тип Транзакции",
            ),
        ),
    ]
