# Generated by Django 4.2.3 on 2025-04-27 14:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "transaction",
            "0003_transaction_financial_report_transaction_updated_by_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="comment",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
