# Generated by Django 4.2.3 on 2023-08-30 20:06

from django.db import migrations, models
import django.db.models.deletion
import apps.medcard.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('action_id', models.AutoField(primary_key=True, serialize=False)),
                ('action_note', models.TextField(blank=True)),
                ('action_quantity', models.PositiveIntegerField()),
                ('action_price', models.FloatField(blank=True, default=0, verbose_name='Цена работы')),
                ('action_price_type', models.CharField(choices=[('Basic', 'Basic'), ('Vip', 'Vip'), ('Discount-price', 'Discount-price'), ('Discount-percent', 'Discount-percent'), ('Zero', 'Zero')], default='Basic', max_length=50)),
                ('action_time', models.PositiveIntegerField(verbose_name='Продолжительность работы')),
                ('action_is_done', models.BooleanField(default=False)),
                ('action_is_paid', models.BooleanField(default=False)),
                ('action_is_cancelled', models.BooleanField(default=False)),
                ('action_finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершён')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('archive', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Работа с карты',
                'verbose_name_plural': 'Работы с карты',
                'permissions': [('add_action', 'Добавить работу с карты'), ('view_action', 'Просмотреть работу с карты'), ('change_action', 'Изменить работу с карты'), ('delete_action', 'Удалить работу с карты')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=apps.medcard.models.PathAndRename('clients/'))),
            ],
            options={
                'verbose_name': 'Рентген',
                'verbose_name_plural': 'Рентгены',
                'permissions': [('add_images', 'Добавить рентген'), ('view_images', 'Просмотреть рентген'), ('change_images', 'Изменить рентген'), ('delete_images', 'Удалить рентген')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='MedicalCard',
            fields=[
                ('card_id', models.AutoField(primary_key=True, serialize=False)),
                ('card_price', models.FloatField(blank=True, default=0, verbose_name='Цена мед-карты')),
                ('card_discount_price', models.FloatField(blank=True, default=0, verbose_name='Скидочная цена мед-карты')),
                ('card_discount_percent', models.IntegerField(blank=True, default=0, verbose_name='Скидочный процент мед-карты')),
                ('card_is_done', models.BooleanField(default=False, verbose_name='Карта завершена')),
                ('card_is_paid', models.BooleanField(default=False, verbose_name='Карта оплачена')),
                ('card_is_cancelled', models.BooleanField(default=False)),
                ('card_finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Карта завершена (время)')),
                ('card_updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('card_created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('archive', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Медицинская карта',
                'verbose_name_plural': 'Медицинские карты',
                'permissions': [('add_medicalcard', 'Добавить медицинскую карту'), ('view_medicalcard', 'Просмотреть медицинскую карту'), ('change_medicalcard', 'Изменить медицинскую карту'), ('delete_medicalcard', 'Удалить медицинскую карту'), ('change_medicalcard_admin', 'Изменить медицинскую карту (админ)'), ('change_medicalcard_cashier', 'Изменить медицинскую карту (кассир)')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Tooth',
            fields=[
                ('tooth_id', models.AutoField(primary_key=True, serialize=False)),
                ('tooth_type', models.CharField(choices=[('Adult', 'Adult'), ('Child', 'Child')], max_length=50)),
                ('tooth_number', models.CharField(max_length=100)),
                ('tooth_image', models.ImageField(upload_to='teeth/')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('archive', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Зуб',
                'verbose_name_plural': 'Зубы',
                'permissions': [('add_tooth', 'Добавить зуб'), ('view_tooth', 'Просмотреть зуб'), ('change_tooth', 'Изменить зуб'), ('delete_tooth', 'Удалить зуб')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('stage_id', models.AutoField(primary_key=True, serialize=False)),
                ('stage_is_done', models.BooleanField(default=False)),
                ('stage_is_paid', models.BooleanField(default=False)),
                ('stage_is_cancelled', models.BooleanField(default=False)),
                ('stage_index', models.PositiveIntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('archive', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stage', to='medcard.medicalcard')),
            ],
            options={
                'verbose_name': 'Этап',
                'verbose_name_plural': 'Этапы',
                'permissions': [('add_stage', 'Добавить этап'), ('view_stage', 'Просмотреть этап'), ('change_stage', 'Изменить этап'), ('delete_stage', 'Удалить этап')],
                'default_permissions': (),
            },
        ),
    ]
