# Generated by Django 4.2.3 on 2023-08-30 20:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('work', '0001_initial'),
        ('disease', '0001_initial'),
        ('client', '0002_initial'),
        ('medcard', '0001_initial'),
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='stage_created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stage_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stage',
            name='tooth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tooth', to='medcard.tooth'),
        ),
        migrations.AddField(
            model_name='medicalcard',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicalcard_client', to='client.client', verbose_name='Карта клиента'),
        ),
        migrations.AddField(
            model_name='images',
            name='card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='medcard.medicalcard'),
        ),
        migrations.AddField(
            model_name='images',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='xray_client', to='client.client'),
        ),
        migrations.AddField(
            model_name='action',
            name='action_created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='action',
            name='action_date',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_date', to='reservation.reservation'),
        ),
        migrations.AddField(
            model_name='action',
            name='action_disease',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_disease', to='disease.disease'),
        ),
        migrations.AddField(
            model_name='action',
            name='action_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_doctor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='action',
            name='action_stage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_stage', to='medcard.stage'),
        ),
        migrations.AddField(
            model_name='action',
            name='action_work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_work', to='work.work'),
        ),
    ]
