# Generated by Django 4.2.3 on 2024-01-20 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medcard', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='action_stage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_stage', to='medcard.stage'),
        ),
        migrations.AlterField(
            model_name='images',
            name='card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='medcard.medicalcard'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stage', to='medcard.medicalcard'),
        ),
    ]
