# Generated by Django 4.2.3 on 2024-05-05 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medcard', '0003_alter_action_action_stage_alter_images_card_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='action_time',
        ),
    ]
