# Generated by Django 4.2.3 on 2025-02-13 21:14

import django.db.models.deletion
from django.db import migrations, models

import apps.medcard.utils


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0005_client_note_alter_client_public_phone_client_and_more"),
        ("medcard", "0004_remove_action_action_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="Xray",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "image",
                    models.ImageField(upload_to=apps.medcard.utils.x_ray_uuid_path),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="x_rays",
                        to="client.client",
                    ),
                ),
                (
                    "medical_card",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="x_rays",
                        to="medcard.medicalcard",
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="x_rays",
                        to="medcard.stage",
                    ),
                ),
                (
                    "tooth",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="x_rays",
                        to="medcard.tooth",
                    ),
                ),
            ],
            options={
                "verbose_name": "Рентген",
                "verbose_name_plural": "Рентген",
                "permissions": [
                    ("add_xray", "Добавить рентген"),
                    ("view_xray", "Просмотреть рентген"),
                    ("change_xray", "Изменить рентген"),
                    ("delete_xray", "Удалить рентген"),
                ],
                "default_permissions": (),
            },
        ),
        migrations.DeleteModel(
            name="Images",
        ),
    ]
