# Generated by Django 4.2.3 on 2023-08-30 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('credit_id', models.AutoField(primary_key=True, serialize=False)),
                ('credit_sum', models.FloatField(default=0, verbose_name='Остаток к оплате')),
                ('credit_price', models.FloatField(default=0, verbose_name='Сумма к оплате кредита')),
                ('credit_type', models.CharField(choices=[('Basic', 'Basic'), ('Vip', 'Vip')], default='Basic', max_length=100, verbose_name='Тип кредита')),
                ('credit_note', models.CharField(blank=True, max_length=255, null=True, verbose_name='Примечания')),
                ('credit_is_paid', models.BooleanField(default=False, verbose_name='Кредит Погашен')),
                ('credit_updated_at', models.DateTimeField(auto_now=True, verbose_name='Кредит обновлён')),
                ('credit_created_at', models.DateTimeField(auto_now_add=True, verbose_name='Кредит создан')),
            ],
            options={
                'verbose_name': 'Кредит',
                'verbose_name_plural': 'Кредиты',
                'permissions': [('add_credit', 'Добавить кредит'), ('view_credit', 'Просмотреть кредит'), ('change_credit', 'Изменить кредит'), ('delete_credit', 'Удалить кредит')],
                'default_permissions': (),
            },
        ),
    ]
