# Generated by Django 4.2.3 on 2023-08-30 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('credit', '0001_initial'),
        ('client', '0001_initial'),
        ('medcard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='credit_action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_action', to='medcard.action', verbose_name='Кредитованная работа'),
        ),
        migrations.AddField(
            model_name='credit',
            name='credit_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_card', to='medcard.medicalcard', verbose_name='Медкарта Заёмщика'),
        ),
        migrations.AddField(
            model_name='credit',
            name='credit_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_client', to='client.client', verbose_name='Заёмщик'),
        ),
    ]
