# Generated by Django 4.2.3 on 2023-08-30 20:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('credit', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='credit_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_user', to=settings.AUTH_USER_MODEL, verbose_name='Кем Выдан'),
        ),
    ]
