# Generated by Django 4.2.3 on 2023-08-30 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('disease_id', models.AutoField(primary_key=True, serialize=False)),
                ('disease_title', models.CharField(max_length=150, verbose_name='Название болезни')),
                ('disease_title_ru', models.CharField(max_length=150, null=True, verbose_name='Название болезни')),
                ('disease_title_en', models.CharField(max_length=150, null=True, verbose_name='Название болезни')),
                ('disease_title_uz', models.CharField(max_length=150, null=True, verbose_name='Название болезни')),
                ('archive', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disease_child', to='disease.disease', verbose_name='Главная Болезнь')),
            ],
            options={
                'verbose_name': 'Болезнь',
                'verbose_name_plural': 'Болезни',
                'permissions': [('add_disease', 'Добавить болезнь'), ('view_disease', 'Просмотреть болезнь'), ('change_disease', 'Изменить болезнь'), ('delete_disease', 'Удалить болезнь')],
                'default_permissions': (),
            },
        ),
    ]
