# Generated by Django 4.2.3 on 2023-08-30 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('storage_id', models.AutoField(primary_key=True, serialize=False)),
                ('storage_item_measure', models.CharField(blank=True, max_length=255, null=True, verbose_name='Единица измерения')),
                ('storage_quantity', models.FloatField(blank=True, null=True, verbose_name='Количество')),
                ('deleted', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Склад',
                'permissions': [('add_storage', 'Добавить в склад'), ('view_storage', 'Просмотреть склад'), ('change_storage', 'Изменить склад'), ('delete_storage', 'Удалить склад')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='StorageHistory',
            fields=[
                ('storage_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('storage_history_type', models.CharField(blank=True, choices=[('add_quantity', 'add_quantity'), ('minus_quantity', 'minus_quantity'), ('give_item', 'give_item'), ('delete', 'delete')], default='', max_length=100)),
                ('storage_history_item_measure', models.CharField(blank=True, max_length=255, null=True, verbose_name='Единица измерения')),
                ('storage_history_item_quantity', models.FloatField(blank=True, null=True, verbose_name='Количество')),
                ('storage_history_item_quantity_before', models.FloatField(blank=True, null=True, verbose_name='Количество до')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Отчет склада',
                'verbose_name_plural': 'Отчет склад',
                'permissions': [('add_storagehistory', 'Добавить отчет склада'), ('view_storagehistory', 'Просмотреть отчет склада'), ('change_storagehistory', 'Изменить отчет склада'), ('delete_storagehistory', 'Удалить отчет склада')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='StorageItem',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название мед. материала')),
                ('item_measure', models.CharField(blank=True, max_length=255, null=True, verbose_name='Единица измерения')),
                ('deleted', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Мед. материал',
                'verbose_name_plural': 'Мед. материалы',
                'permissions': [('add_storageitem', 'Добавить мед.материал'), ('view_storageitem', 'Просмотреть мед.материал'), ('change_storageitem', 'Изменить мед.материал'), ('delete_storageitem', 'Удалить мед.материал')],
                'default_permissions': (),
            },
        ),
    ]
