# Generated by Django 4.2.3 on 2023-08-30 20:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storageitem',
            name='item_created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='storagehistory',
            name='storage_history_created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storage_history_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='storagehistory',
            name='storage_history_created_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storage_history_created_for', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='storagehistory',
            name='storage_history_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storage_history_item', to='storage.storage', verbose_name='Мед. материал'),
        ),
        migrations.AddField(
            model_name='storage',
            name='storage_created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storage_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='storage',
            name='storage_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storage_item', to='storage.storageitem', verbose_name='Мед. материал'),
        ),
    ]
