# Generated by Django 4.2.3 on 2023-08-30 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpensesType',
            fields=[
                ('expenses_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('expenses_type_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Под-тип расхода')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Тип расхода',
                'verbose_name_plural': 'Типы расходов',
                'permissions': [('add_expensestype', 'Добавить тип расхода'), ('view_expensestype', 'Просмотреть тип расхода'), ('change_expensestype', 'Изменить тип расхода'), ('delete_expensestype', 'Удалить тип расхода')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='FinancialReport',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('report_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название расхода')),
                ('report_action_price', models.FloatField(blank=True, null=True, verbose_name='Цена работы медкарты')),
                ('report_work_price', models.FloatField(blank=True, null=True, verbose_name='Цена работы')),
                ('report_sum', models.FloatField(blank=True, null=True, verbose_name='Сумма по которой идет отчет')),
                ('report_note', models.CharField(blank=True, max_length=512, null=True)),
                ('report_quantity', models.IntegerField(blank=True, null=True, verbose_name='Количество товара')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Отчет',
                'verbose_name_plural': 'Отчеты',
                'permissions': [('add_financialreport', 'Добавить финансовый отчет'), ('view_financialreport', 'Просмотреть финансовый отчет'), ('change_financialreport', 'Изменить финансовый отчет'), ('delete_financialreport', 'Удалить финансовый отчет')],
                'default_permissions': (),
            },
        ),
    ]
