# Generated by Django 4.2.3 on 2023-08-30 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expenses', '0001_initial'),
        ('medcard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialreport',
            name='report_action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_action', to='medcard.action', verbose_name='Отчет за работу медкарты'),
        ),
        migrations.AddField(
            model_name='financialreport',
            name='report_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_card', to='medcard.medicalcard', verbose_name='Отчет по медкарте'),
        ),
    ]
