# Generated by Django 4.2.3 on 2023-08-30 20:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('work', '0001_initial'),
        ('user', '0001_initial'),
        ('expenses', '0002_initial'),
        ('client', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialreport',
            name='report_created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Отчет создан пользователем'),
        ),
        migrations.AddField(
            model_name='financialreport',
            name='report_for_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_for_client', to='client.client', verbose_name='Отчет по пациенту'),
        ),
        migrations.AddField(
            model_name='financialreport',
            name='report_for_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_for_user', to=settings.AUTH_USER_MODEL, verbose_name='Отчет по пользователю'),
        ),
        migrations.AddField(
            model_name='financialreport',
            name='report_salary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_salary', to='user.usersalary', verbose_name='Отчет по зарплате'),
        ),
        migrations.AddField(
            model_name='financialreport',
            name='report_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_type', to='expenses.expensestype', verbose_name='Тип расхода'),
        ),
        migrations.AddField(
            model_name='financialreport',
            name='report_work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_work', to='work.work', verbose_name='Отчет за работу'),
        ),
        migrations.AddField(
            model_name='expensestype',
            name='type_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='type_child', to='expenses.expensestype', verbose_name='Тип расхода'),
        ),
    ]
