# Generated by Django 4.2.3 on 2023-11-20 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensestype',
            name='expenses_type_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название под-тип расхода'),
        ),
    ]
