# Generated by Django 4.2.3 on 2024-08-04 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_initial'),
        ('expenses', '0004_alter_expensestype_expenses_type_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialreport',
            name='report_type',
        ),
        migrations.AddField(
            model_name='financialreport',
            name='report_expense_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_types', to='expenses.expensestype', verbose_name='Тип расхода'),
        ),
        migrations.AddField(
            model_name='financialreport',
            name='report_salary_work_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='financialreport',
            name='report_storage_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storage_items', to='storage.storageitem', verbose_name='Отчет за склад'),
        ),
        migrations.AddField(
            model_name='financialreport',
            name='report_sum_usd',
            field=models.FloatField(blank=True, null=True, verbose_name='Сумма по которой идет отчет (USD)'),
        ),
        migrations.AddField(
            model_name='financialreport',
            name='report_usd_cource',
            field=models.FloatField(blank=True, null=True, verbose_name='Курс (USD)'),
        ),
        migrations.AlterField(
            model_name='expensestype',
            name='expenses_type_title',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Название под-тип расхода'),
        ),
        migrations.AlterField(
            model_name='expensestype',
            name='type_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='type_child', to='expenses.expensestype', verbose_name='Главный тип расхода'),
        ),
        migrations.CreateModel(
            name='IncomeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Название')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='expenses.incometype', verbose_name='Главный тип дохода')),
            ],
            options={
                'verbose_name': 'Тип дохода',
                'verbose_name_plural': 'Типы дохода',
                'permissions': [('add_incometype', 'Добавить тип дохода'), ('view_incometype', 'Просмотреть тип дохода'), ('change_incometype', 'Изменить тип дохода'), ('delete_incometype', 'Удалить тип дохода')],
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='financialreport',
            name='report_income_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='income_types', to='expenses.incometype', verbose_name='Тип дохода'),
        ),
    ]
