# Generated by Django 4.2.3 on 2023-08-30 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('specialization_id', models.AutoField(primary_key=True, serialize=False)),
                ('specialization_text', models.CharField(max_length=255, verbose_name='Название специализации')),
                ('specialization_text_ru', models.CharField(max_length=255, null=True, verbose_name='Название специализации')),
                ('specialization_text_en', models.CharField(max_length=255, null=True, verbose_name='Название специализации')),
                ('specialization_text_uz', models.CharField(max_length=255, null=True, verbose_name='Название специализации')),
                ('archive', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Специализация',
                'verbose_name_plural': 'Специализации',
                'permissions': [('add_specialization', 'Добавить специализацию'), ('view_specialization', 'Просмотреть специализацию'), ('change_specialization', 'Изменить специализацию'), ('delete_specialization', 'Удалить специализацию')],
                'default_permissions': (),
            },
        ),
    ]
