# Generated by Django 4.2.3 on 2024-05-05 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specialization', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialization',
            name='archive',
        ),
        migrations.RemoveField(
            model_name='specialization',
            name='deleted',
        ),
    ]
