# Generated by Django 4.2.3 on 2023-08-30 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('notification_message', models.CharField(blank=True, max_length=255, null=True, verbose_name='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'permissions': [('add_notification', 'Добавить уведомление'), ('view_notification', 'Просмотреть уведомление'), ('change_notification', 'Изменить уведомление'), ('delete_notification', 'Удалить уведомление')],
                'default_permissions': (),
            },
        ),
    ]
