# Generated by Django 4.2.3 on 2026-03-30 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_notificationdevice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('reservation_created', 'Reservation created'), ('reservation_approved', 'Reservation approved'), ('reservation_cancelled', 'Reservation cancelled'), ('reservation_cancelled_by_patient', 'Reservation cancelled by patient'), ('reservation_request_created', 'Reservation request created'), ('reservation_reminder', 'Reservation reminder')], default='reservation_created', max_length=64),
        ),
    ]
