# Generated by Django 4.2.3 on 2023-08-30 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('reservation_id', models.AutoField(primary_key=True, serialize=False)),
                ('reservation_notes', models.CharField(blank=True, max_length=255, null=True, verbose_name='Примечания')),
                ('reservation_date', models.DateField(verbose_name='Дата резерва')),
                ('reservation_time', models.TimeField(verbose_name='Время резерва')),
                ('cancelled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reservation_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservation_client', to='client.client', verbose_name='Пациент')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
                'permissions': [('add_reservation', 'Добавить запись'), ('view_reservation', 'Просмотреть запись'), ('change_reservation', 'Изменить запись'), ('delete_reservation', 'Удалить запись')],
                'default_permissions': (),
            },
        ),
    ]
