# Generated by Django 4.2.3 on 2023-11-20 01:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
        ('reservation', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='reservation_time',
            new_name='reservation_start_time',
        ),
        migrations.AddField(
            model_name='reservation',
            name='reservation_end_time',
            field=models.TimeField(default=datetime.datetime(2023, 11, 20, 1, 48, 7, 84314), verbose_name='Время резерва конец'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='reservation_work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservation_work', to='work.work', verbose_name='Работа'),
        ),
    ]
