# Generated by Django 4.2.3 on 2024-08-04 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_client_client_last_viewed_at_and_more'),
        ('reservation', '0004_alter_reservation_reservation_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reservation_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservation_client', to='client.client', verbose_name='Пациент'),
        ),
    ]
