# Generated by Django 4.2.3 on 2025-02-13 21:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("client", "0005_client_note_alter_client_public_phone_client_and_more"),
        ("reservation", "0005_alter_reservation_reservation_client"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="cancelled_by_patient",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="reservation",
            name="is_initial",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="ReservationRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "flutter_reservation_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("approved", "Approved"),
                            ("cancelled", "Cancelled"),
                            ("approved_by_patient", "Approved by patient"),
                            ("cancelled_by_patient", "Cancelled by patient"),
                        ],
                        default="draft",
                        max_length=255,
                    ),
                ),
                (
                    "doctor_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Примечания"
                    ),
                ),
                ("date", models.DateField(verbose_name="Дата резерва")),
                ("time", models.TimeField(verbose_name="Время резерва")),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservation_requests",
                        to="client.client",
                        verbose_name="Пациент",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reservation_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Доктор",
                    ),
                ),
                (
                    "reservation",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservation_request",
                        to="reservation.reservation",
                        verbose_name="Запись",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запрос на запись",
                "verbose_name_plural": "Запросы на запись",
                "permissions": [
                    ("add_reservation", "Добавить запись"),
                    ("view_reservation", "Просмотреть запись"),
                    ("change_reservation", "Изменить запись"),
                    ("delete_reservation", "Удалить запись"),
                ],
                "default_permissions": (),
            },
        ),
    ]
