# Generated by Django 4.2.3 on 2026-03-22 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("work", "0004_rename_work_x_ray_categories_and_more"),
        ("reservation", "0006_reservation_cancelled_by_patient_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservationrequest",
            name="reservation_work",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reservation_requests",
                to="work.work",
                verbose_name="Работа",
            ),
        ),
    ]
