# Generated by Django 4.2.3 on 2023-08-30 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('specialization', '0001_initial'),
        ('category', '0001_initial'),
        ('disease', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=255, null=True)),
                ('changed_pk', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='ID работы')),
                ('work_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название работы')),
                ('work_basic_price', models.FloatField(blank=True, null=True, verbose_name='Базовая цена работы')),
                ('work_vip_price', models.FloatField(blank=True, null=True, verbose_name='ВИП цена работы')),
                ('work_discount_price', models.FloatField(blank=True, null=True, verbose_name='Скидочная цена работы')),
                ('work_discount_percent', models.FloatField(blank=True, null=True, verbose_name='Скидочная цена работы')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Отчет Работ',
                'verbose_name_plural': 'Отчеты Работ',
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('work_id', models.AutoField(primary_key=True, serialize=False)),
                ('work_type', models.CharField(choices=[('Common', 'Common'), ('Tooth', 'Tooth')], max_length=100, verbose_name='Вид Работы')),
                ('work_salary_type', models.CharField(choices=[('Fixed', 'Fixed'), ('Percent', 'Percent'), ('Hybrid', 'Hybrid')], max_length=100, verbose_name='Вид зарплаты')),
                ('work_title', models.CharField(max_length=200, verbose_name='Название работы')),
                ('work_title_ru', models.CharField(max_length=200, null=True, verbose_name='Название работы')),
                ('work_title_en', models.CharField(max_length=200, null=True, verbose_name='Название работы')),
                ('work_title_uz', models.CharField(max_length=200, null=True, verbose_name='Название работы')),
                ('work_time', models.PositiveIntegerField(verbose_name='Время выполнения')),
                ('work_basic_price', models.FloatField(blank=True, default=0, verbose_name='Базовая цена работы')),
                ('work_vip_price', models.FloatField(blank=True, default=0, verbose_name='ВИП цена работы')),
                ('work_null_price', models.IntegerField(default=0, verbose_name='Бесплатная цена работы')),
                ('work_discount_percent', models.FloatField(blank=True, default=0, verbose_name='Скидочный процент работы')),
                ('work_discount_price', models.FloatField(blank=True, default=0, verbose_name='Скидочная цена работы')),
                ('work_fixed_salary_amount', models.FloatField(blank=True, default=0, verbose_name='Сумма фиксированной зарплаты с работы')),
                ('work_hybrid_salary_amount', models.FloatField(blank=True, default=0, verbose_name='Сумма гибридной зарплаты с работы')),
                ('archive', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('category', models.ManyToManyField(blank=True, related_name='work_category', to='category.category', verbose_name='Категория')),
                ('disease', models.ManyToManyField(blank=True, related_name='work_disease', to='disease.disease', verbose_name='Болезнь')),
                ('specialization', models.ManyToManyField(blank=True, related_name='work_specialization', to='specialization.specialization', verbose_name='Специализация')),
            ],
            options={
                'verbose_name': 'Работа',
                'verbose_name_plural': 'Работы',
                'permissions': [('add_work', 'Добавить работу'), ('view_work', 'Просмотреть работу'), ('change_work', 'Изменить работу'), ('delete_work', 'Удалить работу'), ('view_work_private_info', 'Просмотреть приватные данные работы'), ('change_work_private_info', 'Изменить приватные данные работы')],
                'default_permissions': (),
            },
        ),
    ]
