# Generated by Django 4.2.3 on 2024-05-05 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkHistory',
        ),
        migrations.RemoveField(
            model_name='work',
            name='work_time',
        ),
    ]
