# Generated by Django 4.2.3 on 2025-01-16 00:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("category", "0003_xraycategory_and_more"),
        ("work", "0002_delete_workhistory_remove_work_work_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="work",
            name="x_ray_categories",
            field=models.ManyToManyField(
                blank=True,
                related_name="works",
                to="category.xraycategory",
                verbose_name="Категории рентгена",
            ),
        ),
    ]
