# Generated by Django 4.2.3 on 2025-01-18 13:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("category", "0004_rename_xraycategory_printoutcategory_and_more"),
        ("work", "0003_work_x_ray_categories"),
    ]

    operations = [
        migrations.RenameField(
            model_name="work",
            old_name="x_ray_categories",
            new_name="print_out_categories",
        ),
        migrations.AlterField(
            model_name="work",
            name="print_out_categories",
            field=models.ManyToManyField(
                blank=True,
                related_name="works",
                to="category.printoutcategory",
                verbose_name="Категории распечатки",
            ),
        ),
    ]
